"""Render human- and agent-readable Markdown from canonical artifacts.

Rendered Markdown is a *view*: it is regenerated on every build and always states
where each statement came from.  Two labels are used consistently:

  [source: ...]     grounded in the document, with a locator
  [SYNTHESIS]       generated by the analysing model, never in the papers verbatim
"""
from __future__ import annotations

import os
import time
from typing import Any, Dict, Iterable, List, Optional

from . import PIPELINE_VERSION, SCHEMA_VERSION, fsutil, ids, manifest, store

BASIS_LABEL = {
    "author_stated": "authors state",
    "shown_by_result": "shown by result",
    "agent_inferred": "MODEL INFERENCE",
    "unavailable": "not available in document",
}


def cite(loc: Dict[str, Any]) -> str:
    """Compact, greppable citation string used everywhere in rendered output."""
    parts = [loc.get("paper_id", "?")]
    section = " > ".join(loc.get("section_path") or [])
    if section:
        parts.append("§" + section[:60])
    if loc.get("page_label"):
        parts.append("p." + str(loc["page_label"]))
    elif loc.get("page_index") is not None:
        parts.append("page#%d" % (loc["page_index"] + 1))
    if loc.get("unit_id"):
        parts.append(loc["unit_id"])
    if loc.get("line_start"):
        parts.append("line %d" % loc["line_start"])
    if loc.get("char_start") is not None:
        parts.append("c%d-%d" % (loc["char_start"], loc.get("char_end") or loc["char_start"]))
    if loc.get("extraction_method") == "ocr":
        parts.append("OCR")
    return "[" + " ".join(parts) + "]"


def _stmt(field: Optional[Dict[str, Any]]) -> str:
    if not field or not field.get("text"):
        return "_not available_"
    basis = BASIS_LABEL.get(field.get("basis"), field.get("basis") or "?")
    line = "%s  \n  _(%s" % (field["text"], basis)
    if field.get("confidence") is not None:
        line += ", confidence %.2f" % field["confidence"]
    line += ")_"
    if field.get("rationale") and field.get("basis") == "agent_inferred":
        line += "  \n  _rationale: %s_" % field["rationale"]
    locs = field.get("locators") or []
    if locs:
        line += "  \n  " + " ".join(cite(l) for l in locs[:4])
    return line


def _stmt_list(items: Optional[List[Dict[str, Any]]], bullet: str = "-") -> str:
    if not items:
        return "_none recorded_\n"
    out = []
    for item in items:
        out.append("%s %s" % (bullet, _stmt(item).replace("\n", "\n  ")))
    return "\n".join(out) + "\n"


def _named_list(items: Optional[List[Dict[str, Any]]]) -> str:
    if not items:
        return "_none recorded_\n"
    lines = []
    for item in items:
        bits = [("**%s**" % item["name"])]
        for key in ("kind", "role", "version", "size"):
            if item.get(key):
                bits.append("%s: %s" % (key, item[key]))
        if item.get("detail"):
            bits.append(item["detail"])
        label = BASIS_LABEL.get(item.get("basis"), item.get("basis") or "")
        line = "- " + " — ".join(bits) + "  _(%s)_" % label
        if item.get("locators"):
            line += " " + " ".join(cite(l) for l in item["locators"][:2])
        lines.append(line)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- KB_INDEX.md
def render_kb_index(kb_dir: str, cfg: Dict[str, Any], man: Dict[str, Any], papers: List[Dict[str, Any]],
                    claims: List[Dict[str, Any]], relations: List[Dict[str, Any]],
                    topics: List[Dict[str, Any]], overview: Optional[Dict[str, Any]]) -> str:
    years = [p["metadata"].get("year") for p in papers if p["metadata"].get("year")]
    quality = {}
    for paper in papers:
        key = (paper.get("parse") or {}).get("text_quality", "unknown")
        quality[key] = quality.get(key, 0) + 1
    pending = manifest.model_work_pending(man, cfg)
    pending_lines = [
        "- **%s**: %s" % (stage, ("all papers" if pids == ["*"] else "%d paper(s)" % len(pids)))
        for stage, pids in pending.items() if pids
    ]
    claim_by_paper: Dict[str, int] = {}
    for claim in claims:
        claim_by_paper[claim["paper_id"]] = claim_by_paper.get(claim["paper_id"], 0) + 1

    lines = [
        "# Knowledge base index",
        "",
        "> Generated by the `paperbase` skill. Canonical knowledge is the files listed below;",
        "> `index/kb.sqlite` is a derived accelerator and can be rebuilt with `kb reindex`.",
        "> Source documents are never modified: they stay in `%s`." % man["paper_dir"],
        "",
        "| | |",
        "|---|---|",
        "| Papers (active) | %d |" % len(papers),
        "| Year span | %s |" % ("%s–%s" % (min(years), max(years)) if years else "unknown"),
        "| Retrieval units | %d |" % sum(len(store.read_units(kb_dir, p["paper_id"])) for p in papers),
        "| Atomic claims | %d |" % len(claims),
        "| Relations | %d |" % len(relations),
        "| Topic syntheses | %d |" % len(topics),
        "| Text quality | %s |" % ", ".join("%s: %d" % kv for kv in sorted(quality.items())),
        "| Schema / pipeline | %s / %s |" % (SCHEMA_VERSION, PIPELINE_VERSION),
        "| Last update | %s |" % man.get("updated"),
        "",
        "## How to use this KB (for agents)",
        "",
        "1. **Best first move for a question:** `kb context <kb> \"<question>\" --budget 8000` —",
        "   returns passages, claims, profiles, relations and a topic synthesis with citations,",
        "   plus counterevidence and follow-up pointers.",
        "2. **Lexical search:** `kb search <kb> \"<terms>\"` (`--kind units|claims|papers|topics`,",
        "   filters: `--paper --year --type --method --dataset --concept --min-confidence`).",
        "3. **Drill into one paper:** `kb show-paper <kb> <paper_id>` or read",
        "   `papers/<paper_id>/paper.md`; the full normalized text is `docs/<paper_id>/text.txt`",
        "   and every locator's `char_start`/`char_end` indexes into that file.",
        "4. **Drill into one claim:** `kb show-claim <kb> <claim_id>` (prints the claim, its",
        "   locators, the quoted passage and related claims).",
        "5. **Trust rules:** statements labelled `MODEL INFERENCE` or `[SYNTHESIS]` are analysis,",
        "   not source text. Claims carry `evidence_status` and `is_primary_evidence` — a claim",
        "   from an introduction is that paper *citing someone else*, not its own result.",
        "",
        "## Layout",
        "",
        "```",
        "corpus/papers.jsonl        machine-readable manifest (one row per paper)",
        "docs/<paper_id>/           text.txt (canonical offsets), blocks.jsonl, units.jsonl, parse.json",
        "papers/<paper_id>/         paper.md, profile.json, claims.jsonl",
        "relations/                 relations.jsonl (model+human), families.jsonl, tombstoned.jsonl",
        "synthesis/                 CORPUS_OVERVIEW.md, topics/, terminology.json, indexes/",
        "overrides/                 human corrections (authoritative, never regenerated)",
        "state/                     manifest.json (fingerprints), audit.jsonl, journal.json",
        "reports/                   build/update/validation reports",
        "index/kb.sqlite            derived FTS5 index (gitignored)",
        "```",
        "",
    ]
    if overview and overview.get("field_summary"):
        lines += ["## Corpus overview [SYNTHESIS]", "",
                  overview["field_summary"][:1500], "",
                  "Full synthesis: [synthesis/CORPUS_OVERVIEW.md](synthesis/CORPUS_OVERVIEW.md)", ""]
    if topics:
        lines += ["## Topics", ""]
        for topic in sorted(topics, key=lambda t: t["name"].lower()):
            lines.append("- [%s](synthesis/topics/%s.md) — %d paper(s)"
                         % (topic["name"], topic["topic_id"], len(topic.get("papers") or [])))
        lines.append("")
    lines += ["## Papers", "",
              "| paper_id | year | type | title | text | units | claims | analysis |",
              "|---|---|---|---|---|---|---|---|"]
    for paper in sorted(papers, key=lambda p: (-(p["metadata"].get("year") or 0), p["paper_id"])):
        meta = paper["metadata"]
        state = paper.get("analysis_state") or {}
        lines.append("| [`%s`](papers/%s/paper.md) | %s | %s | %s | %s | %d | %d | profile:%s claims:%s |" % (
            paper["paper_id"], paper["paper_id"], meta.get("year") or "?",
            (meta.get("document_type") or "?").replace("_", " "),
            (meta.get("title") or "")[:70].replace("|", "/"),
            (paper.get("parse") or {}).get("text_quality", "?"),
            (paper.get("parse") or {}).get("n_units", 0),
            claim_by_paper.get(paper["paper_id"], 0),
            state.get("profile", "missing"), state.get("claims", "missing")))
    lines.append("")
    families = [r for r in relations if r["relation"] in ("supplement-of", "preprint-of", "possible-duplicate-of", "version-of")]
    if families:
        lines += ["## Document families", ""]
        for rel in families:
            lines.append("- `%s` **%s** `%s` — %s _(%s, confidence %.2f)_" % (
                rel["source_paper_id"], rel["relation"], rel.get("target_paper_id") or "UNRESOLVED",
                rel.get("rationale", ""), rel.get("origin"), rel.get("confidence") or 0))
        lines.append("")
    if pending_lines:
        lines += ["## Pending model-dependent work", "",
                  "These stages need an analysing agent (see `kb tasks`):", ""] + pending_lines + [""]
    if man.get("unsupported") or man.get("archives"):
        lines += ["## Files present but not parsed", ""]
        for item in man.get("archives") or []:
            lines.append("- `%s` — companion archive (%d entries catalogued, not parsed)"
                         % (item["path"], len(item.get("contents") or [])))
        for item in man.get("unsupported") or []:
            lines.append("- `%s` — %s" % (item["path"], item["reason"]))
        lines.append("")
    tombs = man.get("tombstones") or []
    if tombs:
        lines += ["## Tombstoned documents", "",
                  "Knowledge derived from these documents was removed; ids are retained so old",
                  "citations resolve to an explicit 'removed' record.", ""]
        for tomb in tombs[-20:]:
            lines.append("- `%s` (%s) — %s" % (tomb["paper_id"], tomb.get("source_path"), tomb["reason"]))
        lines.append("")
    warn_papers = [p for p in papers if (p.get("parse") or {}).get("warnings")]
    if warn_papers:
        lines += ["## Extraction warnings", ""]
        for paper in warn_papers:
            for warning in (paper.get("parse") or {}).get("warnings", [])[:3]:
                lines.append("- `%s`: %s" % (paper["paper_id"], warning))
        lines.append("")
    path = os.path.join(kb_dir, "KB_INDEX.md")
    fsutil.atomic_write_text(path, "\n".join(lines))
    return path


# ---------------------------------------------------------------- paper.md
def render_paper(kb_dir: str, paper: Dict[str, Any], claims: List[Dict[str, Any]],
                 relations: List[Dict[str, Any]], profile: Optional[Dict[str, Any]]) -> str:
    pid = paper["paper_id"]
    meta = paper["metadata"]
    prov = paper.get("metadata_provenance") or {}
    parse = paper.get("parse") or {}
    lines = [
        "# %s" % (meta.get("title") or pid),
        "",
        "`paper_id: %s`" % pid,
        "",
        "## Bibliographic record",
        "",
        "| field | value | source | confidence |",
        "|---|---|---|---|",
    ]
    for field in ("title", "authors", "year", "venue", "doi", "document_type", "publication_status"):
        value = meta.get(field)
        if isinstance(value, list):
            value = ", ".join(value)
        pv = prov.get(field) or {}
        lines.append("| %s | %s | %s | %s |" % (
            field, str(value or "_unknown_")[:120].replace("|", "/"),
            pv.get("source", "-"), pv.get("confidence", "-")))
    lines += [
        "",
        "- **Source file:** `%s` (never modified by paperbase)" % paper.get("source_path"),
        "- **Content sha256:** `%s`" % (paper.get("content_sha256") or "")[:16],
        "- **Identity basis:** %s" % paper.get("identity_basis"),
        "- **Parser:** %s %s (%s), %s pages, %d units, text quality **%s**%s" % (
            parse.get("adapter"), parse.get("adapter_version"), parse.get("layout_signal"),
            parse.get("n_pages"), parse.get("n_units", 0), parse.get("text_quality"),
            ", OCR RECOMMENDED" if parse.get("needs_ocr") else ""),
        "- **Normalized text:** `docs/%s/text.txt` — all locator offsets index into this file" % pid,
        "",
    ]
    if paper.get("family"):
        lines += ["### Document family", ""]
        for fam in paper["family"]:
            lines.append("- **%s** → `%s` _(%s, confidence %.2f)_" % (
                fam["relation"], fam["target_paper_id"], fam["origin"], fam["confidence"]))
        lines.append("")
    if paper.get("override_notes"):
        lines += ["### Human corrections applied", ""] + \
                 ["- %s" % note for note in paper["override_notes"]] + [""]
    if parse.get("warnings"):
        lines += ["### Extraction warnings", ""] + ["- %s" % w for w in parse["warnings"]] + [""]
    if parse.get("sections"):
        lines += ["### Detected top-level sections", "",
                  ", ".join("`%s`" % s for s in parse["sections"][:25]), ""]
    if meta.get("abstract"):
        lines += ["### Abstract (verbatim from source)", "", "> " + meta["abstract"][:1800].replace("\n", "\n> "), ""]

    if not profile:
        lines += ["## Research profile", "",
                  "_Not yet generated._ Run `kb tasks %s --stage profile --paper %s` and follow the"
                  " emitted work order; then `kb ingest`." % (kb_dir, pid), ""]
    else:
        analysis = profile["analysis"]
        gen = profile["generated_by"]
        lines += [
            "## Research profile",
            "",
            "_Generated by %s using prompt %s (version %s) at %s._%s" % (
                gen["model_id"], gen["prompt"], gen["prompt_version"], gen["generated_at"],
                " **Reviewed by a human.**" if gen.get("reviewed_by_human") else ""),
            "",
            "### Problem and contribution", "",
            "**Research problem.** " + _stmt(analysis.get("research_problem")), "",
            "**Motivation.** " + _stmt(analysis.get("motivation")), "",
            "**Main contribution.** " + _stmt(analysis.get("main_contribution")), "",
            "**Study type.** %s — %s _(%s)_" % (
                (analysis.get("study_type") or {}).get("value", "?"),
                (analysis.get("study_type") or {}).get("detail") or "",
                BASIS_LABEL.get((analysis.get("study_type") or {}).get("basis"), "?")), "",
            "### Research questions / hypotheses", "",
            _stmt_list(analysis.get("research_questions")),
            _stmt_list(analysis.get("hypotheses")),
            "### Methods and design", "",
            _named_list(analysis.get("methods")),
            "**Experimental design.** " + _stmt(analysis.get("experimental_design")), "",
            "**Domain / population / task.** " + _stmt(analysis.get("population_or_task")), "",
            "**Data sources.**", "", _named_list(analysis.get("data_sources")),
            "**Models / interventions.**", "", _named_list(analysis.get("models_or_interventions")),
            "**Baselines and controls.**", "", _named_list(analysis.get("baselines_and_controls")),
            "**Evaluation metrics.**", "", _named_list(analysis.get("evaluation_metrics")),
            "### Findings", "",
            "**Primary.**", "", _stmt_list(analysis.get("primary_findings")),
            "**Secondary.**", "", _stmt_list(analysis.get("secondary_findings")),
            "**Negative / null.**", "", _stmt_list(analysis.get("negative_or_null_findings")),
            "**Quantitative results.**", "", _stmt_list(analysis.get("quantitative_results")),
            "### Scope, assumptions, limitations", "",
            "**Assumptions.**", "", _stmt_list(analysis.get("assumptions")),
            "**Scope / boundary conditions.**", "", _stmt_list(analysis.get("scope_and_boundary_conditions")),
            "**Limitations stated by the authors.**", "", _stmt_list(analysis.get("limitations_stated")),
            "**Additional limitations inferred by the analysing model [SYNTHESIS].**", "",
            _stmt_list(analysis.get("limitations_inferred")),
            "**Threats to validity [SYNTHESIS].**", "", _stmt_list(analysis.get("threats_to_validity")),
            "### Reproducibility", "",
        ]
        repro = analysis.get("reproducibility") or {}
        lines += [
            "- Code available: %s %s" % (repro.get("code_available"), repro.get("code_location") or ""),
            "- Data available: %s %s" % (repro.get("data_available"), repro.get("data_location") or ""),
            "", _stmt(repro.get("notes")) if repro.get("notes") else "",
            "", "### Future work stated by the authors", "", _stmt_list(analysis.get("future_work_stated")),
            "### Unresolved questions raised by this paper", "", _stmt_list(analysis.get("unresolved_questions")),
            "### Retrieval terms", "",
            ", ".join("`%s`" % t for t in (analysis.get("retrieval_terms") or [])) or "_none_", "",
        ]
        if analysis.get("unavailable_fields"):
            lines += ["### Not determinable from this document", "",
                      ", ".join(analysis["unavailable_fields"]), ""]
        if analysis.get("extraction_warnings"):
            lines += ["### Analysis warnings", ""] + ["- %s" % w for w in analysis["extraction_warnings"]] + [""]

    mine = [c for c in claims if c["paper_id"] == pid]
    lines += ["## Atomic claims (%d)" % len(mine), ""]
    if not mine:
        lines.append("_No claims extracted yet._\n")
    for claim in mine:
        primary = claim.get("is_primary_evidence", True)
        lines += [
            "### `%s`" % claim["claim_id"],
            "",
            "**%s**" % claim["statement"],
            "",
            "- type: `%s` · evidence: `%s` · polarity: `%s` · evidence type: `%s`" % (
                claim["claim_type"], claim["evidence_status"], claim["polarity"],
                claim.get("evidence_type")),
            "- primary evidence of this paper: **%s**%s" % (
                "yes" if primary else "NO — this paper is reporting other work",
                (" (cited source: %s)" % claim["cited_source"]) if claim.get("cited_source") else ""),
        ]
        for key in ("subject", "intervention", "comparator", "outcome"):
            if claim.get(key):
                lines.append("- %s: %s" % (key, claim[key]))
        effect = claim.get("effect") or {}
        if any(effect.values()):
            lines.append("- effect: direction=%s magnitude=%s uncertainty=%s significant=%s" % (
                effect.get("direction"), effect.get("magnitude"), effect.get("uncertainty"),
                effect.get("significant")))
        if claim.get("conditions"):
            lines.append("- conditions: %s" % "; ".join(claim["conditions"]))
        if claim.get("qualifiers"):
            lines.append("- qualifiers: %s" % "; ".join(claim["qualifiers"]))
        if claim.get("derivation"):
            lines.append("- derivation: %s" % claim["derivation"])
        if claim.get("human_override"):
            lines.append("- **corrected by a human override**")
        lines.append("- confidence: %.2f" % (claim.get("confidence") or 0))
        for loc in claim.get("support") or []:
            lines.append("- evidence %s" % cite(loc))
            lines.append("  > %s" % (loc.get("excerpt") or "").replace("\n", " ")[:400])
        lines.append("")
    rels = [r for r in relations if pid in (r.get("source_paper_id"), r.get("target_paper_id"))]
    lines += ["## Relations involving this paper (%d)" % len(rels), ""]
    for rel in rels:
        arrow = "→" if rel["source_paper_id"] == pid else "←"
        other = rel.get("target_paper_id") if rel["source_paper_id"] == pid else rel["source_paper_id"]
        lines.append("- **%s** %s `%s` — %s _(%s, confidence %.2f)_" % (
            rel["relation"], arrow, other or "UNRESOLVED", rel.get("rationale", ""),
            rel.get("origin"), rel.get("confidence") or 0))
    lines += ["", "---", "",
              "_Rendered from `profile.json`, `claims.jsonl` and `corpus/papers.jsonl`; "
              "regenerated on every build. Edit knowledge through `overrides/`, not here._"]
    path = store.paper_md_path(kb_dir, pid)
    fsutil.ensure_dir(os.path.dirname(path))
    fsutil.atomic_write_text(path, "\n".join(lines))
    return path


# ---------------------------------------------------------------- synthesis
def _points(title: str, items: Optional[List[Dict[str, Any]]]) -> List[str]:
    if not items:
        return []
    out = ["### %s" % title, ""]
    for item in items:
        line = "- %s" % item["text"]
        if item.get("evidence_strength"):
            line += " _(evidence: %s)_" % item["evidence_strength"]
        out.append(line)
        out.append("  - claims: %s" % ", ".join("`%s`" % c for c in item.get("claim_ids") or []))
        if item.get("note"):
            out.append("  - note: %s" % item["note"])
    out.append("")
    return out


def render_topic(kb_dir: str, topic: Dict[str, Any]) -> str:
    gen = topic.get("generated_by") or {}
    lines = [
        "# Topic: %s" % topic["name"],
        "",
        "`topic_id: %s`  ·  papers: %s" % (topic["topic_id"], ", ".join("`%s`" % p for p in topic.get("papers") or [])),
        "",
        "> **[SYNTHESIS]** This page is model-generated analysis across papers, not source text.",
        "> Generated by %s with %s (v%s) at %s." % (
            gen.get("model_id"), gen.get("prompt"), gen.get("prompt_version"), gen.get("generated_at")),
        "",
        topic.get("summary") or "",
        "",
    ]
    if topic.get("aliases"):
        lines += ["**Also called:** " + ", ".join(topic["aliases"]), ""]
    for label, key in (("Key concepts", "key_concepts"), ("Methods", "methods"),
                       ("Datasets and benchmarks", "datasets_and_benchmarks")):
        if topic.get(key):
            lines += ["**%s:** %s" % (label, ", ".join(topic[key])), ""]
    lines += _points("Areas of agreement", topic.get("agreements"))
    lines += _points("Qualified agreement", topic.get("qualified_agreements"))
    lines += _points("Genuine disagreements", topic.get("genuine_disagreements"))
    lines += _points("Apparent disagreements, explained", topic.get("apparent_disagreements_explained"))
    lines += _points("Common limitations", topic.get("common_limitations"))
    lines += _points("Understudied conditions", topic.get("understudied_conditions"))
    lines += _points("Open questions", topic.get("open_questions"))
    if topic.get("chronology"):
        lines += ["### Chronological development", ""]
        for item in topic["chronology"]:
            lines.append("- **%s** — %s (%s)" % (item.get("year"), item["development"],
                                                 ", ".join("`%s`" % p for p in item.get("paper_ids") or [])))
        lines.append("")
    matrix = topic.get("comparison_matrix")
    if matrix and matrix.get("columns"):
        lines += ["### Comparison: %s" % matrix.get("dimension", ""), "",
                  "| paper | " + " | ".join(matrix["columns"]) + " |",
                  "|---" * (len(matrix["columns"]) + 1) + "|"]
        for row in matrix.get("rows") or []:
            cells = ["" if c is None else str(c) for c in row.get("cells") or []]
            lines.append("| `%s` | %s |" % (row["paper_id"], " | ".join(cells)))
        lines.append("")
    if topic.get("warnings"):
        lines += ["### Warnings", ""] + ["- %s" % w for w in topic["warnings"]] + [""]
    path = os.path.join(store.topics_dir(kb_dir), topic["topic_id"] + ".md")
    fsutil.ensure_dir(os.path.dirname(path))
    fsutil.atomic_write_text(path, "\n".join(lines))
    return path


def render_overview(kb_dir: str, overview: Dict[str, Any]) -> str:
    gen = overview.get("generated_by") or {}
    lines = [
        "# Corpus overview",
        "",
        "> **[SYNTHESIS]** Model-generated analysis across the whole corpus. Every point cites the",
        "> claim ids it rests on; follow them to the papers and passages.",
        "> Generated by %s with %s (v%s) at %s." % (
            gen.get("model_id"), gen.get("prompt"), gen.get("prompt_version"), gen.get("generated_at")),
        "",
        overview.get("field_summary", ""),
        "",
    ]
    if overview.get("scope_note"):
        lines += ["**Scope of this corpus.** " + overview["scope_note"], ""]
    if overview.get("topic_map"):
        lines += ["## Topic map", ""]
        for topic in overview["topic_map"]:
            lines.append("- [%s](topics/%s.md)%s — %s" % (
                topic["name"], topic["topic_id"],
                (" › " + ", ".join(topic.get("subtopics") or [])) if topic.get("subtopics") else "",
                ", ".join("`%s`" % p for p in topic.get("paper_ids") or [])))
        lines.append("")
    lines += _points("Strong agreement", overview.get("strong_agreement"))
    lines += _points("Qualified agreement", overview.get("qualified_agreement"))
    lines += _points("Genuine contradictions", overview.get("genuine_contradictions"))
    lines += _points("Apparent contradictions explained by different conditions",
                     overview.get("apparent_contradictions_explained"))
    lines += _points("Evidence-strength assessment", overview.get("evidence_strength_assessment"))
    lines += _points("Common limitations", overview.get("common_limitations"))
    lines += _points("Failure modes", overview.get("failure_modes"))
    lines += _points("Understudied conditions", overview.get("understudied_conditions"))
    lines += _points("Open questions", overview.get("open_questions"))
    lines += _points("Research gaps", overview.get("research_gaps"))
    for label, key in (("Foundational papers", "foundational_papers"),
                       ("Papers that materially changed the field", "field_changing_papers")):
        if overview.get(key):
            lines += ["## %s" % label, ""]
            for item in overview[key]:
                lines.append("- `%s` — %s %s" % (item["paper_id"], item["why"],
                                                 " ".join("`%s`" % c for c in item.get("claim_ids") or [])))
            lines.append("")
    if overview.get("dependencies"):
        lines += ["## Dependencies between methods, datasets and findings", ""]
        for dep in overview["dependencies"]:
            lines.append("- `%s` **%s** `%s` — %s" % (dep["from"], dep["kind"], dep["to"], dep.get("note") or ""))
        lines.append("")
    if overview.get("warnings"):
        lines += ["## Warnings", ""] + ["- %s" % w for w in overview["warnings"]] + [""]
    path = os.path.join(kb_dir, "synthesis", "CORPUS_OVERVIEW.md")
    fsutil.atomic_write_text(path, "\n".join(lines))
    return path


def render_terminology(kb_dir: str, terminology: List[Dict[str, Any]]) -> str:
    lines = ["# Terminology and synonyms", "",
             "Canonical terms, aliases and — importantly — places where papers use the same word",
             "for different things. Query expansion in `kb search`/`kb context` uses this file.", ""]
    if not terminology:
        lines.append("_Not yet generated (run the terminology part of the topic-synthesis stage)._")
    for term in sorted(terminology, key=lambda t: t["term"].lower()):
        lines.append("## %s" % term["term"])
        if term.get("canonical"):
            lines.append("- canonical form: **%s**" % term["canonical"])
        if term.get("acronym_of"):
            lines.append("- acronym of: %s" % term["acronym_of"])
        if term.get("synonyms"):
            lines.append("- synonyms: %s" % ", ".join(term["synonyms"]))
        if term.get("definition"):
            lines.append("- definition: %s %s" % (term["definition"],
                                                  " ".join("`%s`" % c for c in term.get("definition_claim_ids") or [])))
        for conflict in term.get("conflicting_definitions") or []:
            lines.append("- ⚠ conflicting definition in `%s`: %s %s" % (
                conflict["paper_id"], conflict["definition"],
                " ".join("`%s`" % c for c in conflict.get("claim_ids") or [])))
        if term.get("paper_ids"):
            lines.append("- used by: %s" % ", ".join("`%s`" % p for p in term["paper_ids"]))
        lines.append("")
    path = os.path.join(kb_dir, "synthesis", "TERMINOLOGY.md")
    fsutil.atomic_write_text(path, "\n".join(lines))
    return path


_INDEX_SPECS = (
    ("methods", "Methods and algorithms", ("methods",), ("method", "algorithm", "tool", "technique")),
    ("datasets", "Datasets and data sources", ("data_sources",), ("dataset", "data", "corpus", "reads")),
    ("models", "Models and interventions", ("models_or_interventions",), ("model", "architecture", "intervention")),
    ("benchmarks", "Benchmarks and metrics", ("evaluation_metrics",), ("benchmark", "metric", "evaluation")),
)


def render_entity_indexes(kb_dir: str, papers: List[Dict[str, Any]], claims: List[Dict[str, Any]]) -> List[str]:
    """Deterministic aggregation of profile/claim entities - no model needed."""
    written = []
    profiles = {}
    for paper in papers:
        profile = store.read_profile(kb_dir, paper["paper_id"])
        if profile:
            profiles[paper["paper_id"]] = profile
    for slug, title, profile_keys, claim_keys in _INDEX_SPECS:
        table: Dict[str, Dict[str, Any]] = {}
        for pid, profile in profiles.items():
            analysis = profile.get("analysis") or {}
            for key in profile_keys:
                for item in analysis.get(key) or []:
                    entry = table.setdefault(item["name"].strip(), {"papers": set(), "claims": set(), "roles": set()})
                    entry["papers"].add(pid)
                    if item.get("role"):
                        entry["roles"].add(item["role"])
        claim_field = {"methods": "methods", "datasets": "datasets", "models": "entities",
                       "benchmarks": "concepts"}[slug]
        for claim in claims:
            for name in claim.get(claim_field) or []:
                entry = table.setdefault(str(name).strip(), {"papers": set(), "claims": set(), "roles": set()})
                entry["papers"].add(claim["paper_id"])
                entry["claims"].add(claim["claim_id"])
        lines = ["# %s index" % title, "",
                 "Aggregated deterministically from `profile.json` and `claims.jsonl` "
                 "(no model involved in this page).", "",
                 "| name | papers | roles | claims |", "|---|---|---|---|"]
        for name, entry in sorted(table.items(), key=lambda kv: (-len(kv[1]["papers"]), kv[0].lower())):
            if not name:
                continue
            lines.append("| %s | %s | %s | %s |" % (
                name[:70].replace("|", "/"),
                ", ".join("`%s`" % p for p in sorted(entry["papers"])[:8]),
                ", ".join(sorted(entry["roles"]))[:60],
                ", ".join("`%s`" % c for c in sorted(entry["claims"])[:6])))
        if len(lines) == 6:
            lines.append("| _nothing recorded yet_ | | | |")
        path = os.path.join(kb_dir, "synthesis", "indexes", "%s.md" % slug)
        fsutil.atomic_write_text(path, "\n".join(lines) + "\n")
        written.append(path)
    concept_counts: Dict[str, Dict[str, set]] = {}
    for claim in claims:
        for concept in claim.get("concepts") or []:
            entry = concept_counts.setdefault(str(concept).strip().lower(), {"papers": set(), "claims": set()})
            entry["papers"].add(claim["paper_id"])
            entry["claims"].add(claim["claim_id"])
    lines = ["# Concept index", "", "| concept | papers | claims |", "|---|---|---|"]
    for concept, entry in sorted(concept_counts.items(), key=lambda kv: (-len(kv[1]["claims"]), kv[0])):
        lines.append("| %s | %s | %s |" % (concept[:60], len(entry["papers"]),
                                           ", ".join("`%s`" % c for c in sorted(entry["claims"])[:8])))
    if len(lines) == 4:
        lines.append("| _nothing recorded yet_ | | |")
    path = os.path.join(kb_dir, "synthesis", "indexes", "concepts.md")
    fsutil.atomic_write_text(path, "\n".join(lines) + "\n")
    written.append(path)
    return written


def render_all(kb_dir: str, cfg: Dict[str, Any], man: Dict[str, Any], papers: List[Dict[str, Any]],
               claims: List[Dict[str, Any]], relations: List[Dict[str, Any]],
               topics: List[Dict[str, Any]], overview: Optional[Dict[str, Any]],
               terminology: List[Dict[str, Any]]) -> List[str]:
    written = [render_kb_index(kb_dir, cfg, man, papers, claims, relations, topics, overview)]
    for paper in papers:
        written.append(render_paper(kb_dir, paper, claims, relations,
                                    store.read_profile(kb_dir, paper["paper_id"])))
    for topic in topics:
        written.append(render_topic(kb_dir, topic))
    if overview:
        written.append(render_overview(kb_dir, overview))
    written.append(render_terminology(kb_dir, terminology))
    written.extend(render_entity_indexes(kb_dir, papers, claims))
    fsutil.atomic_write_json(os.path.join(kb_dir, "state", "versions.json"), {
        "schema_version": SCHEMA_VERSION,
        "pipeline_version": PIPELINE_VERSION,
        "config_hash": man.get("config_hash"),
        "rendered_at": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime()),
    })
    return written


def write_update_report(kb_dir: str, report: Dict[str, Any]) -> str:
    lines = [
        "# %s report" % report["mode"].capitalize(),
        "",
        "- KB: `%s`" % report["kb_dir"],
        "- Papers directory: `%s`" % report["paper_dir"],
        "- Elapsed: %.2fs" % report.get("elapsed_s", 0),
        "",
        "## Document changes",
        "",
        "| change | count | papers |",
        "|---|---|---|",
    ]
    for key in ("added", "modified", "renamed", "unchanged", "reparsed", "removed", "failed", "id_changed"):
        items = report.get(key) or []
        detail = ", ".join(
            "`%s`" % (i.get("paper_id") or i.get("path") or i.get("to")) for i in items[:8])
        lines.append("| %s | %d | %s |" % (key, len(items), detail))
    lines += ["", "## Model-dependent work pending", ""]
    pending = report.get("model_work_pending") or {}
    if not any(pending.values()):
        lines.append("None — every analysis stage is current. **A no-op update performs zero model work.**")
    for stage, pids in pending.items():
        if pids:
            lines.append("- `%s`: %s" % (stage, "whole corpus" if pids == ["*"] else ", ".join("`%s`" % p for p in pids)))
    if report.get("stale_corpus_stages"):
        lines += ["", "## Corpus stages needing regeneration", "",
                  "These depend on all papers' claims; a change to any paper invalidates them.", ""]
        for stage in report["stale_corpus_stages"]:
            lines.append("- `%s`" % stage)
    lines += ["", "## Index counts", ""]
    for key, value in sorted((report.get("counts") or {}).items()):
        lines.append("- %s: %d" % (key, value))
    if report.get("overrides_applied"):
        lines += ["", "## Human overrides applied", ""]
        for key, value in sorted(report["overrides_applied"].items()):
            lines.append("- %s: %d" % (key, value))
    if report.get("failed"):
        lines += ["", "## Failures", ""]
        for item in report["failed"]:
            lines.append("- `%s`: %s" % (item["path"], item["error"]))
    if report.get("warnings"):
        lines += ["", "## Warnings", ""] + ["- %s" % w for w in report["warnings"]]
    path = os.path.join(kb_dir, "reports", "last_%s_report.md" % report["mode"])
    fsutil.atomic_write_text(path, "\n".join(lines) + "\n")
    fsutil.atomic_write_json(os.path.join(kb_dir, "reports", "last_%s_report.json" % report["mode"]), report)
    return path
